export const datas = [
    {
        title: "Urgent Need for Blockchain Innovator at Pokhara",
        companyName: "Builder",
        job_role: "Blockchain Developer",
        date: "Jan 25th 2024",
        location: "Pokhara",
        type: "Internship",
        status: "Pending",
        salary: "30,000 - 40,000",
        workHours: "9 AM - 5 PM",
        description: "Join Builder as a Blockchain Developer, where you will dive deep into the world of decentralized technologies. In this role, you'll be involved in designing, developing, and implementing blockchain solutions. You will learn about smart contracts, decentralized applications (dApps), and the intricacies of blockchain security. Builder prides itself on a collaborative and innovative environment, where fresh ideas are welcomed, and professional growth is encouraged through mentorship and hands-on experience.",
        skillsRequired: ["JavaScript", "Solidity", "Blockchain Basics", "Problem Solving"]
    },
    {
        title: "Frontend Developer Wanted: Join the Tech Revolution in Kathmandu!",
        companyName: "Tech Solutions",
        job_role: "Frontend Developer",
        date: "Feb 10th 2024",
        location: "Kathmandu",
        type: "Junior",
        status: "Pending",
        salary: "35,000 - 45,000",
        workHours: "9 AM - 5 PM",
        description: "As a Frontend Developer at Tech Solutions, you will have the opportunity to work on a variety of projects that focus on creating user-friendly interfaces. This position will help you enhance your skills in modern frontend technologies while collaborating with designers and backend developers. You'll be responsible for turning designs into interactive web pages, ensuring responsiveness and performance. The company is known for fostering a creative and open environment, allowing you to experiment with new ideas and technologies.",
        skillsRequired: ["React", "HTML", "CSS", "JavaScript"]
    },
    {
        title: "Innovate Your Future: Backend Developer Needed in Lalitpur!",
        companyName: "Innovatech",
        job_role: "Backend Developer",
        date: "Mar 15th 2024",
        location: "Lalitpur",
        type: "Mid-Junior",
        status: "No longer accepting applications",
        salary: "40,000 - 50,000",
        workHours: "9 AM - 5 PM",
        description: "Innovatech offers a stimulating environment for Backend Developers looking to expand their skill set. You will work on building robust server-side applications and APIs while learning about scalable architecture and cloud services. The team emphasizes code quality and best practices, encouraging you to engage in code reviews and pair programming sessions. This position will not only enhance your technical skills but also immerse you in a culture that values continuous learning and innovation.",
        skillsRequired: ["Node.js", "Express", "MongoDB", "API Development"]
    },
    {
        title: "Calling All Solana Developers: Join Creative Labs in Pokhara!",
        companyName: "Creative Labs",
        job_role: "Solana Developer",
        date: "Apr 5th 2024",
        location: "Pokhara",
        type: "Internship",
        status: "Pending",
        salary: "30,000 - 40,000",
        workHours: "9 AM - 5 PM",
        description: "At Creative Labs, you'll embark on a journey to become proficient in Solana development. You'll work on real-world blockchain projects, implementing features and functionalities that leverage the power of Solana's high-speed infrastructure. This internship provides a unique opportunity to learn about the latest in blockchain technology while being part of a passionate team dedicated to pushing the boundaries of innovation. The company prides itself on its supportive environment where you can freely share ideas and grow.",
        skillsRequired: ["Rust", "Solana", "Web Development", "Team Collaboration"]
    },
    {
        title: "Join the Blockchain Revolution: Junior Developer Wanted in Butwal!",
        companyName: "CodeCrafters",
        job_role: "Blockchain Developer",
        date: "May 1st 2024",
        location: "Butwal",
        type: "Junior",
        status: "Pending",
        salary: "30,000 - 40,000",
        workHours: "9 AM - 5 PM",
        description: "Join CodeCrafters as a Blockchain Developer, where you will engage in developing cutting-edge blockchain applications. In this role, you will gain hands-on experience in creating secure, efficient, and scalable blockchain solutions. You will work closely with other developers and stakeholders to understand requirements and implement innovative features. The company fosters a culture of collaboration and encourages personal growth, making it an ideal place for emerging talent in the tech space.",
        skillsRequired: ["Blockchain Fundamentals", "JavaScript", "APIs", "Git"]
    },
    {
        title: "Unlock Your Potential: Frontend Developer Needed in Biratnagar!",
        companyName: "NextGen Tech",
        job_role: "Frontend Developer",
        date: "Jun 12th 2024",
        location: "Biratnagar",
        type: "Mid-Junior",
        status: "No longer accepting applications",
        salary: "35,000 - 45,000",
        workHours: "9 AM - 5 PM",
        description: "At NextGen Tech, you'll be part of a dynamic team working on cutting-edge frontend technologies. This role will help you refine your skills in building responsive, visually appealing web applications while working closely with UX/UI designers. You'll learn about industry best practices and contribute to various projects, enhancing user experiences across multiple platforms. The company values innovation and creativity, providing an environment where your ideas can flourish.",
        skillsRequired: ["React", "Redux", "JavaScript", "UI/UX Principles"]
    },
    {
        title: "Data-Driven Opportunities: Python Developer Intern in Nepalgunj!",
        companyName: "DataDriven",
        job_role: "Python Developer (AI)",
        date: "Jul 22nd 2024",
        location: "Nepalgunj",
        type: "Internship",
        status: "Pending",
        salary: "30,000 - 40,000",
        workHours: "9 AM - 5 PM",
        description: "DataDriven is seeking an aspiring Python Developer to join their AI team. This internship will provide you with valuable experience in data analysis, machine learning, and AI model development. You will work on real projects, gaining insights into how data-driven decisions are made. The company emphasizes continuous learning, allowing you to enhance your technical skills while contributing to meaningful projects that impact various sectors.",
        skillsRequired: ["Python", "Data Science", "Machine Learning", "Pandas"]
    },
    {
        title: "Shape the Future: Fullstack Developer Position Open in Bhaktapur!",
        companyName: "SoftSolutions",
        job_role: "Fullstack Developer",
        date: "Aug 30th 2024",
        location: "Bhaktapur",
        type: "Junior",
        status: "Pending",
        salary: "35,000 - 45,000",
        workHours: "9 AM - 5 PM",
        description: "As a Fullstack Developer at SoftSolutions, you will have the chance to work on end-to-end development projects. You will gain experience in both frontend and backend technologies while collaborating with a diverse team. The company is dedicated to fostering talent and innovation, providing resources for professional development and skill enhancement. You'll be encouraged to share your ideas and implement solutions that improve the overall project outcomes.",
        skillsRequired: ["JavaScript", "Node.js", "React", "SQL"]
    },
    {
        title: "WebWorks Needs You: Solana Developer Internship in Dharan!",
        companyName: "WebWorks",
        job_role: "Solana Developer",
        date: "Sep 18th 2024",
        location: "Dharan",
        type: "Internship",
        status: "No longer accepting applications",
        salary: "30,000 - 40,000",
        workHours: "9 AM - 5 PM",
        description: "At WebWorks, you will dive into the world of blockchain technology by focusing on Solana development. This internship offers you the chance to contribute to projects that utilize Solana's unique capabilities. You'll collaborate with experienced developers and gain insights into blockchain architecture and application design. The company is committed to creating a collaborative environment that encourages learning and experimentation.",
        skillsRequired: ["Rust", "Solana", "Web Development", "Team Collaboration"]
    },
    {
        title: "Join the Tech Titans: Frontend Developer Role in Hetauda!",
        companyName: "Tech Titans",
        job_role: "Frontend Developer",
        date: "Oct 25th 2024",
        location: "Hetauda",
        type: "Mid-Junior",
        status: "Pending",
        salary: "35,000 - 45,000",
        workHours: "9 AM - 5 PM",
        description: "At Tech Titans, you will work with a talented team of Frontend Developers to create engaging web applications. This position will allow you to enhance your skills in JavaScript and related frameworks while also understanding the importance of user experience and interface design. The company fosters an innovative culture where your ideas can lead to impactful changes in the projects you work on.",
        skillsRequired: ["React", "JavaScript", "CSS", "Responsive Design"]
    }
];
